version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    
    # Primary container image where all commands run
    
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: habitica
          CODECOV_TOKEN: 4b9df79e-7c66-4f45-bfa0-3c79ee860721
    
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: habitica
          POSTGRES_DB: api-habits_test
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: rubocop
          command: |
            bundle exec rubocop
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      
      - run:
          name: Install heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Heroku login
          command: |
            cat >~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            EOF

      - run: 
          name: Tests
          command: |
            heroku config --app $HEROKU_APP_NAME | sed 's/:  */=/g; /^=/d' >> .env  
            sed -i '/SECRET_KEY_BASE/d' .env     
            sed -i '/DATABASE_URL/d' .env     
            heroku local:run bundle exec rake RAILS_ENV=test test 
            rm .env

      - run:
          filters:
            branches:
              only: development
          name: Deploy to heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              git push https://git.heroku.com/$HEROKU_APP_NAME.git development:master
              heroku pg:reset --app $HEROKU_APP_NAME --confirm $HEROKU_APP_NAME
              heroku run rake db:migrate --app $HEROKU_APP_NAME
              heroku run rake db:seed --app $HEROKU_APP_NAME
            fi

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
